spring:
  datasource:
    url: ${ENV_JDBC_URL}
    username: ${ENV_JDBC_USERNAME}
    password: ${ENV_JDBC_PASSWORD}
  data:
    redis:
      host: ${ENV_REDIS_HOST}
      port: ${ENV_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
          order_inserts: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

cache:
  min_percent_hashes: 20
  capacity: 1000

scheduler:
  cron: '0 0 0 * * *'
  lifetime_days: 365

generator:
  batch:
    size: 10000

server:
  url: 'http://localhost:8080'
  port: 8080

logging:
  level:
    root: info